import re
import sys
import urllib.request

# 锁定版本：升级时改这里，跑完审查 ass-loader.js 的 diff。
# 下载非压缩版 (ass.js)，这样更容易精准修改，防止误删代码。
ASSJS_VERSION = "0.1.4"
URL = f"https://cdn.jsdelivr.net/npm/assjs@{ASSJS_VERSION}/dist/ass.js"
OUTPUT_FILE = "ass-loader.js"

# 上游 dist 末尾的 ES module 导出，例如 `export { ASS as default };`
EXPORT_PATTERN = re.compile(r'^export\s*\{\s*ASS\s+as\s+default\s*\};?\s*$', re.MULTILINE)


def fix_ass_loader():
    print(f"⬇️  正在下载 assjs@{ASSJS_VERSION}: {URL} ...")
    with urllib.request.urlopen(URL) as response:
        content = response.read().decode('utf-8')

    print(f"📦 下载完成，原始大小: {len(content)} 字符")

    # 去掉 ES module 导出。content script 不能用模块语法，改由 IIFE 末尾挂到 window。
    content, count = EXPORT_PATTERN.subn('', content)
    if count != 1:
        raise RuntimeError(f"期望找到 1 处 'export {{ ASS as default }}'，实际 {count} 处，上游结构可能变了")
    if re.search(r'^\s*export\s', content, re.MULTILINE):
        raise RuntimeError("仍有未处理的 export 语句，上游结构可能变了")

    final_code = f"""// --------------------------------------------------
// Patched ASS-Loader (No Module Syntax)
// Generated by build.py from assjs@{ASSJS_VERSION}. Do not edit by hand.
// --------------------------------------------------
(function() {{
    const define = undefined; // 禁用 AMD 加载器探测
    const module = undefined; // 禁用 CommonJS 探测

    // --- 原始库代码开始 ---
{content}
    // --- 原始库代码结束 ---

    window.ASS = ASS;
}})();
"""

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(final_code)

    print(f"✅ 已生成: {OUTPUT_FILE}")
    print("👉 请审查 diff，然后刷新 Chrome 扩展和 YouTube 页面。")


if __name__ == "__main__":
    # Windows 中文控制台默认 GBK，打印 emoji 会抛 UnicodeEncodeError
    for stream in (sys.stdout, sys.stderr):
        stream.reconfigure(encoding='utf-8', errors='replace')
    try:
        fix_ass_loader()
    except Exception as e:
        print(f"❌ 失败: {e}", file=sys.stderr)
        sys.exit(1)
