// 把 node_modules 里锁定版本的 assjs 官方 IIFE 构建复制成 ass-loader.js。
// dist/ass.global.js 会定义全局 `var ASS`，同一扩展的 content script 共享全局作用域，
// content.js 直接通过 window.ASS 使用，不需要任何补丁。
// 用法：改 package.json 里的 assjs 版本，跑 npm install 和 npm run vendor，然后审查 diff。

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const pkgDir = path.join(root, 'node_modules', 'assjs');
const { version } = require(path.join(pkgDir, 'package.json'));

const source = fs.readFileSync(path.join(pkgDir, 'dist', 'ass.global.js'), 'utf8');
// 上游一旦改了构建形式（比如不再输出全局变量），在这里就失败，而不是生成一个加载后没有 ASS 的文件
if (!/^var ASS = \(function \(\) \{/.test(source)) {
    console.error('assjs dist/ass.global.js 不再以 `var ASS = (function () {` 开头，上游构建形式可能变了');
    process.exit(1);
}

const header = `// assjs@${version} dist/ass.global.js (MIT, see ass-loader.LICENSE)\n`
    + '// Generated by `npm run vendor`. Do not edit by hand.\n';
fs.writeFileSync(path.join(root, 'ass-loader.js'), header + source.replace(/\r\n/g, '\n'));
fs.copyFileSync(path.join(pkgDir, 'LICENSE'), path.join(root, 'ass-loader.LICENSE'));

console.log(`ass-loader.js <- assjs@${version}`);
